LOGIN_ERROR = 'ログインできませんでした'
PASSWORD_ERROR = 'パスワードが違います'
USERNAME_INTEGRITY_ERROR = 'そのユーザー名は既に使用されています'
EMAIL_INTEGRITY_ERROR = 'そのメールアドレスは既に使用されています'
API_ERROR = '書籍情報を取得できませんでした'
ISBN_ERROR = 'ISBN コードが正しくありません'
BOOK_INTEGRITY_ERROR = '登録済みの書籍です'
